#include "troubleshooting.h"

// generated by ai, cause I ain't gonna format all that printf stuff - not for something that already exists.
// I'm all for learning, but I need an inprogram hexdump like... now... not after 3 more projects where
// things snowball. I might re-write it by hand later to add some additional bits and bobs I want... not sure yet...
void hex_dump(const void *buffer, size_t size)
{
    const uint8_t *data = (const uint8_t *)buffer;
    size_t i, j;
    printf("--- BUFFER HEX DUMP ---\n");
    for (i = 0; i < size; i += 16)
    {
        // 1. Print the current memory offset (8-character width hex)
        printf("%08zX  ", i);

        // 2. Print Hexadecimal representation of bytes
        for (j = 0; j < 16; j++)
        {
            if (i + j < size)
            {
                printf("%02X ", data[i + j]);
            }
            else
            {
                printf("   "); // Spaces for alignment if buffer ends early
            }
            if (j == 7)
                printf(" "); // Visual separator between 8-byte blocks
        }

        printf(" |");

        // 3. Print readable ASCII characters
        for (j = 0; j < 16; j++)
        {
            if (i + j < size)
            {
                uint8_t ch = data[i + j];
                // Print only printable characters; replace others with a dot '.'
                printf("%c", isprint(ch) ? ch : '.');
            }
        }
        printf("|\n");
    }
}